#pragma once

#include "sxml_core.hpp"
#include "sxml_fundamental.hpp"
#include "sxml_string.hpp"
#include "sxml_vector.hpp"
#include "sxml_deque.hpp"
#include "sxml_list.hpp"
#include "sxml_array.hpp"
#include "sxml_forward_list.hpp"
#include "sxml_set.hpp"
#include "sxml_map.hpp"
#include "sxml_unordered_map.hpp"
#include "sxml_unordered_set.hpp"
#include "sxml_fusion.hpp"
